//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskFrame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskFrame.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeskFrame is already running.
        /// </summary>
        public static string DeskFrame_AlreadyRunning {
            get {
                return ResourceManager.GetString("DeskFrame.AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a file or folder.
        /// </summary>
        public static string Deskframe_DropaFileOrFolder {
            get {
                return ResourceManager.GetString("Deskframe.DropaFileOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating requires administrator privileges.
        /// </summary>
        public static string Deskframe_Update_DialogContent {
            get {
                return ResourceManager.GetString("Deskframe.Update.DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update. Check for update on start and every 6 hours.
        /// </summary>
        public static string DeskFrameFrameSettings_AutoUpdate {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change icon size.
        /// </summary>
        public static string DeskFrameFrameSettings_ChangeIconSizeDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ChangeIconSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default frame style.
        /// </summary>
        public static string DeskFrameFrameSettings_DefaultFrameStyle {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DefaultFrameStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on desktop to toggle hide every frame.
        /// </summary>
        public static string DeskFrameFrameSettings_DoubleClickHide {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DoubleClickHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAG.
        /// </summary>
        public static string DeskFrameFrameSettings_Drag {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to visit GitHub page.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_DoubleClickToGithub {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.DoubleClickToGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Move any window with right‑click drag.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_Feature1 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Resize any window from edges and corners.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_Feature2 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Scroll between virtual desktops with gestures.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_Feature3 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Change window opacity (Alt + mouse wheel).
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_Feature4 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Scroll through windows with mouse wheel.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_Feature5 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main features:.
        /// </summary>
        public static string DeskFrameFrameSettings_DragWinToolTip_MainFeatures {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.DragWinToolTip.MainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces Windows search with Everything search.
        /// </summary>
        public static string DeskFrameFrameSettings_EQSToolTip_Feature1 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings_EQSToolTip_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview images and videos.
        /// </summary>
        public static string DeskFrameFrameSettings_EQSToolTip_Feature2 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings_EQSToolTip_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator in search bar.
        /// </summary>
        public static string DeskFrameFrameSettings_EQSToolTip_Feature3 {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings_EQSToolTip_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string DeskFrameFrameSettings_ExportSettings {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with .
        /// </summary>
        public static string DeskFrameFrameSettings_MadewithSpace {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.MadewithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage frame.
        /// </summary>
        public static string DeskFrameFrameSettings_ManageFrameButton {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ManageFrameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all frames.
        /// </summary>
        public static string DeskFrameFrameSettings_ReloadAllFramesButton {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ReloadAllFramesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename items, ENTER to confirm.
        /// </summary>
        public static string DeskFrameFrameSettings_RenameFilesDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.RenameFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [File] Change the order of the file.
        /// </summary>
        public static string DeskFrameFrameSettings_ReorderDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings_ReorderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset default style.
        /// </summary>
        public static string DeskFrameFrameSettings_ResetDefaultStyle {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ResetDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCROLL.
        /// </summary>
        public static string DeskFrameFrameSettings_Scroll {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOWN] on title bar: send window back.
        /// </summary>
        public static string DeskFrameFrameSettings_ScrollDownDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ScrollDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UP] on title bar: bring window forward.
        /// </summary>
        public static string DeskFrameFrameSettings_ScrollUpDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.ScrollUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To search move the cursor over the frame you want to search in and start typing.
        /// </summary>
        public static string DeskFrameFrameSettings_SearchDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings_SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Frame] Snap frame with 10 pixel distance.
        /// </summary>
        public static string DeskFrameFrameSettings_SnapDescription {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.SnapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeskFrame settings.
        /// </summary>
        public static string DeskFrameFrameSettings_TitleBarText {
            get {
                return ResourceManager.GetString("DeskFrameFrameSettings.TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string FrameGridView_DateModified {
            get {
                return ResourceManager.GetString("FrameGridView.DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrameGridView_Name {
            get {
                return ResourceManager.GetString("FrameGridView.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FrameGridView_Size {
            get {
                return ResourceManager.GetString("FrameGridView.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active color (hex).
        /// </summary>
        public static string FrameSettings_ActiveColor {
            get {
                return ResourceManager.GetString("FrameSettings.ActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation speed:.
        /// </summary>
        public static string FrameSettings_AnimationSpeed {
            get {
                return ResourceManager.GetString("FrameSettings.AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand on cursor over.
        /// </summary>
        public static string FrameSettings_AutoExpandonCursor {
            get {
                return ResourceManager.GetString("FrameSettings.AutoExpandonCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color (hex): .
        /// </summary>
        public static string FrameSettings_BackgroundColor {
            get {
                return ResourceManager.GetString("FrameSettings.BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color (hex):.
        /// </summary>
        public static string FrameSettings_BorderColor {
            get {
                return ResourceManager.GetString("FrameSettings.BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File items.
        /// </summary>
        public static string FrameSettings_CategoryFileItems {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryFileItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string FrameSettings_CategoryMiscellaneous {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar.
        /// </summary>
        public static string FrameSettings_CategoryTitleBar {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string FrameSettings_CategoryWindow {
            get {
                return ResourceManager.GetString("FrameSettings.CategoryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        public static string FrameSettings_ChangeFolder {
            get {
                return ResourceManager.GetString("FrameSettings.ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change style.
        /// </summary>
        public static string FrameSettings_ChangeStyle {
            get {
                return ResourceManager.GetString("FrameSettings.ChangeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show folder size in menu.
        /// </summary>
        public static string FrameSettings_CheckFolderSize {
            get {
                return ResourceManager.GetString("FrameSettings.CheckFolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder inside window.
        /// </summary>
        public static string FrameSettings_FolderOpenInsideFrame {
            get {
                return ResourceManager.GetString("FrameSettings.FolderOpenInsideFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string FrameSettings_Font {
            get {
                return ResourceManager.GetString("FrameSettings.Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string FrameSettings_FrameHeight {
            get {
                return ResourceManager.GetString("FrameSettings.FrameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string FrameSettings_FrameWidth {
            get {
                return ResourceManager.GetString("FrameSettings.FrameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable grayscale.
        /// </summary>
        public static string FrameSettings_GrayscaleEnable {
            get {
                return ResourceManager.GetString("FrameSettings.GrayscaleEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale only when frame is inactive.
        /// </summary>
        public static string FrameSettings_GrayScaleEnabledInactiveOnly {
            get {
                return ResourceManager.GetString("FrameSettings.GrayScaleEnabledInactiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray level:.
        /// </summary>
        public static string FrameSettings_GrayScaleMaxLevel {
            get {
                return ResourceManager.GetString("FrameSettings.GrayScaleMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide files (regex):.
        /// </summary>
        public static string FrameSettings_HideFilesRegex {
            get {
                return ResourceManager.GetString("FrameSettings.HideFilesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide icons on inactive window.
        /// </summary>
        public static string FrameSettings_HideTitleBarIconsWhenInactive {
            get {
                return ResourceManager.GetString("FrameSettings.HideTitleBarIconsWhenInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size:.
        /// </summary>
        public static string FrameSettings_IconSize {
            get {
                return ResourceManager.GetString("FrameSettings.IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle opacity:.
        /// </summary>
        public static string FrameSettings_IdleOpacityLabel {
            get {
                return ResourceManager.GetString("FrameSettings.IdleOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position X:.
        /// </summary>
        public static string FrameSettings_PositionX {
            get {
                return ResourceManager.GetString("FrameSettings.PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Y: .
        /// </summary>
        public static string FrameSettings_PositionY {
            get {
                return ResourceManager.GetString("FrameSettings.PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string FrameSettings_RevertButton {
            get {
                return ResourceManager.GetString("FrameSettings.RevertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string FrameSettings_Searchdot {
            get {
                return ResourceManager.GetString("FrameSettings.Searchdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string FrameSettings_ShowFileExtensionIcon {
            get {
                return ResourceManager.GetString("FrameSettings.ShowFileExtensionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files (regex):.
        /// </summary>
        public static string FrameSettings_ShowFilesRegex {
            get {
                return ResourceManager.GetString("FrameSettings.ShowFilesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files.
        /// </summary>
        public static string FrameSettings_ShowHiddenFilesIcon {
            get {
                return ResourceManager.GetString("FrameSettings.ShowHiddenFilesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon text.
        /// </summary>
        public static string FrameSettings_ShowIconText {
            get {
                return ResourceManager.GetString("FrameSettings.ShowIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last accessed items first.
        /// </summary>
        public static string FrameSettings_ShowLastAccessedItem {
            get {
                return ResourceManager.GetString("FrameSettings.ShowLastAccessedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible on virtual desktop:.
        /// </summary>
        public static string FrameSettings_ShowOnVirtualDesktopLabel {
            get {
                return ResourceManager.GetString("FrameSettings.ShowOnVirtualDesktopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All (or e.g. 1,2,3).
        /// </summary>
        public static string FrameSettings_ShowOnVirtualDesktopPlaceHolder {
            get {
                return ResourceManager.GetString("FrameSettings.ShowOnVirtualDesktopPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show shortcut arrow.
        /// </summary>
        public static string FrameSettings_ShowShortcutArrow {
            get {
                return ResourceManager.GetString("FrameSettings.ShowShortcutArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize width to fit icon size.
        /// </summary>
        public static string FrameSettings_SnapWidthToIconWidth {
            get {
                return ResourceManager.GetString("FrameSettings.SnapWidthToIconWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve space for scrollbar.
        /// </summary>
        public static string FrameSettings_SnapWidthToIconWidth_PlusScrollbarWidth {
            get {
                return ResourceManager.GetString("FrameSettings.SnapWidthToIconWidth_PlusScrollbarWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alignment:.
        /// </summary>
        public static string FrameSettings_TextAlignment {
            get {
                return ResourceManager.GetString("FrameSettings.TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color (hex):.
        /// </summary>
        public static string FrameSettings_TextColor {
            get {
                return ResourceManager.GetString("FrameSettings.TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text shadow color (hex):.
        /// </summary>
        public static string FrameSettings_TextShadowColor {
            get {
                return ResourceManager.GetString("FrameSettings.TextShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text size:.
        /// </summary>
        public static string FrameSettings_TextSize {
            get {
                return ResourceManager.GetString("FrameSettings.TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar icons:.
        /// </summary>
        public static string FrameSettings_TitleBarIcons {
            get {
                return ResourceManager.GetString("FrameSettings.TitleBarIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame settings.
        /// </summary>
        public static string FrameSettings_TitleBarText {
            get {
                return ResourceManager.GetString("FrameSettings.TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar text:.
        /// </summary>
        public static string FrameSettings_TitleBarTextText {
            get {
                return ResourceManager.GetString("FrameSettings.TitleBarTextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first folder or file you drag in decides the frame type. There are two types:.
        /// </summary>
        public static string FrameTypeFlyout_Description {
            get {
                return ResourceManager.GetString("FrameTypeFlyout.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates shortcuts from anywhere to access files and folders. When you drag another file or folder into it, it creates a shortcut of the item..
        /// </summary>
        public static string FrameTypeFlyout_Description_FileTypeDescription {
            get {
                return ResourceManager.GetString("FrameTypeFlyout.Description.FileTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the contents of a folder. When you drag another file or folder into it, it moves the item inside that folder..
        /// </summary>
        public static string FrameTypeFlyout_Description_FolderTypeDescription {
            get {
                return ResourceManager.GetString("FrameTypeFlyout.Description.FolderTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string FrameTypeFlyout_File {
            get {
                return ResourceManager.GetString("FrameTypeFlyout.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string FrameTypeFlyout_Folder {
            get {
                return ResourceManager.GetString("FrameTypeFlyout.Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a folder.
        /// </summary>
        public static string showFolderInGrid_DropFolder {
            get {
                return ResourceManager.GetString("showFolderInGrid.DropFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change view.
        /// </summary>
        public static string TitleBarContextMenu_ChangeView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string TitleBarContextMenu_CustomItemOrder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.CustomItemOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TitleBarContextMenu_CustomItemOrder_DeleteOrder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.CustomItemOrder.DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string TitleBarContextMenu_CustomItemOrder_ToggleSwitch_Disable {
            get {
                return ResourceManager.GetString("TitleBarContextMenu_CustomItemOrder_ToggleSwitch_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string TitleBarContextMenu_CustomItemOrder_ToggleSwitch_Enable {
            get {
                return ResourceManager.GetString("TitleBarContextMenu_CustomItemOrder_ToggleSwitch_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details view.
        /// </summary>
        public static string TitleBarContextMenu_DetailsView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.DetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string TitleBarContextMenu_FileExtensions {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Settings.
        /// </summary>
        public static string TitleBarContextMenu_FrameSettings {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.FrameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid view.
        /// </summary>
        public static string TitleBarContextMenu_GridView {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files.
        /// </summary>
        public static string TitleBarContextMenu_HiddenFiles {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: .
        /// </summary>
        public static string TitleBarContextMenu_Info_Files {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders: .
        /// </summary>
        public static string TitleBarContextMenu_Info_Folders {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Size: .
        /// </summary>
        public static string TitleBarContextMenu_Info_FolderSize {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hidden).
        /// </summary>
        public static string TitleBarContextMenu_Info_HiddenFiles {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: .
        /// </summary>
        public static string TitleBarContextMenu_Info_LastUpdated {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Info.LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock frame.
        /// </summary>
        public static string TitleBarContextMenu_LockFrame {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.LockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string TitleBarContextMenu_OpenFolder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string TitleBarContextMenu_Reload {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TitleBarContextMenu_Remove {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove it?.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Content {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_No {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Title {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TitleBarContextMenu_RemoveMessageBox_Yes {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.RemoveMessageBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string TitleBarContextMenu_Sortby {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Ascending {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_DateCreated {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_DateModified {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Descending {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FileSize {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FileType {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_First {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_Last {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderIder_None {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderIder.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder order.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_FolderOrder {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.FolderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TitleBarContextMenu_Sortby_Name {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.Sortby.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock frame.
        /// </summary>
        public static string TitleBarContextMenu_UnlockFrame {
            get {
                return ResourceManager.GetString("TitleBarContextMenu.UnlockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add frame.
        /// </summary>
        public static string TrayContextMenu_AddFrame {
            get {
                return ResourceManager.GetString("TrayContextMenu.AddFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string TrayContextMenu_CheckUpdateButton {
            get {
                return ResourceManager.GetString("TrayContextMenu.CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayContextMenu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TrayContextMenu_Settings {
            get {
                return ResourceManager.GetString("TrayContextMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on login.
        /// </summary>
        public static string TrayContextMenu_StartOnLogin {
            get {
                return ResourceManager.GetString("TrayContextMenu.StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit github.
        /// </summary>
        public static string TrayContextMenu_VisitGithub {
            get {
                return ResourceManager.GetString("TrayContextMenu.VisitGithub", resourceCulture);
            }
        }
    }
}
